### PR TITLE
Tca 41/error page2

### PR DESCRIPTION
**Pull request by CodeLeom**

### CODE REVIEW

**Comment by codejagaban** [comment]
@CodeLeom is this ready?

**Comment by CodeLeom** [comment]
Test it sir

**Comment by codejagaban** [comment]
@CodeLeom  the deployment is failing, can you merge the `develop` branch to this branch?

**Comment by CodeLeom** [comment]
Let me try it


*Aransiola Ayodele I.*
*Technical Support Specialist* | website <https://leomtechnologies.com/>
LinkedIn <https://www.linkedin.com/company/leom-technologies-limited> |
Twitter <https://twitter.com/leomofthings> | Github
<https://github.com/CodeLeom>

*This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error, please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
kindly delete the content of this e-mail from your inbox. If you are not
the intended recipient you are notified that disclosing, copying,
distributing or taking any action in reliance on the contents of this
information is strictly prohibited.*

**Pull request merged**
